FROM php:7.4-cli
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libzip-dev \
    && docker-php-ext-install zip

COPY --from=composer:2.0 /usr/bin/composer /usr/bin/composer

WORKDIR /app
